[phases.setup]
nixPkgs = ["nodejs_22", "chromium"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm i --omit=dev"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"
